#!/bin/sh

lint=$(which swiftlint)

if [[ -e "${lint}" ]]; then
	echo "Starting SwiftLint..."
else
	echo "SwiftLint not found. Please download from https://github.com/realm/SwiftLint"
fi

RESULT=$($lint lint --quiet)

if [ "$RESULT" == '' ]; then
  printf "\e[32mSwiftLint Finished.\e[39m\n"
else
  echo ""
  printf "\e[41mSwiftLint Failed.\e[49m Please check below:\n"
while read -r line; do
FILEPATH=$(echo $line | cut -d : -f 1)
    L=$(echo $line | cut -d : -f 2)
    C=$(echo $line | cut -d : -f 3)
    TYPE=$(echo $line | cut -d : -f 4 | cut -c 2-)
    MESSAGE=$(echo $line | cut -d : -f 5 | cut -c 2-)
    DESCRIPTION=$(echo $line | cut -d : -f 6 | cut -c 2-)
    if [ "$TYPE" == 'error' ]; then
      printf "\n  \e[31m$TYPE\e[39m\n"
    else
      printf "\n  \e[33m$TYPE\e[39m\n"
    fi
    printf "    \e[90m$FILEPATH:$L:$C\e[39m\n"
    printf "    $MESSAGE - $DESCRIPTION\n"
  done <<< "$RESULT"

printf "\PUSH ABORTED. Please fix them before pushing your code.\n"
printf "Run `swiftlint lint --fix` to fix autofixable errors.\n"
printf "Then run `swiftlint lint` to see what's left to be fixed.\n"

exit 1
fi
